{
 "title": "E6Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "QPE Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Flow",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "telemetrydb",
     "expression": {
      "from": { "property": { "name": "sink_output", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "sink_output\n| where $__timeFilter(event_time)\n| summarize count() by bin(event_time, 1m)\n| order by event_time asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "All Sink Telemetry Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "database": "telemetrydb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "sink_output\r\n| where $__timeFilter(event_time)\r\n| extend kusto_ingestion_time = ingestion_time()\r\n| extend totaltimediff = datetime_diff('second', kusto_ingestion_time, event_time)\r\n| project event_time, totaltimediff\r\n| summarize percentile(totaltimediff, 95) by bin(event_time, 1m)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "All Sink Latency 95th Percentile",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "telemetrydb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "sink_output\r\n| where $__timeFilter(event_time)\r\n| extend kusto_ingestion_time = ingestion_time()\r\n| extend totaltimediff = datetime_diff('second', kusto_ingestion_time, event_time)\r\n| summarize percentiles(totaltimediff, 95)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Error Events Telemetry Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "telemetrydb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "error_events\r\n| where $__timeFilter(event_time)\r\n| extend kusto_ingestion_time = ingestion_time()\r\n| extend totaltimediff = datetime_diff('second', kusto_ingestion_time, event_time)\r\n| project event_time, totaltimediff\r\n| summarize percentile(totaltimediff, 95) by bin(event_time, 1m)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Error Events Latency 95th Percentile",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "telemetrydb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "error_events\r\n| where $__timeFilter(event_time)\r\n| extend kusto_ingestion_time = ingestion_time()\r\n| extend totaltimediff = datetime_diff('second', kusto_ingestion_time, event_time)\r\n| summarize percentiles(totaltimediff, 95)",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Component Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Ingestion Event Hub Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 37 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "centralindia",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "centralindia",
        "resourceGroup": "observabilitytest",
        "resourceName": "observabilityingestns",
        "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
    }
   ]
  },
  {
   "title": "Ingestion EH Throttled Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 37 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "centralindia",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "centralindia",
        "resourceGroup": "observabilitytest",
        "resourceName": "observabilityingestns",
        "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
    }
   ]
  },
  {
   "title": "Stream Analytics Watermark Delay",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 49 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutputWatermarkDelaySeconds",
      "metricNamespace": "microsoft.streamanalytics/streamingjobs",
      "region": "centralindia",
      "resources": [
       {
        "metricNamespace": "Microsoft.StreamAnalytics/streamingjobs",
        "region": "centralindia",
        "resourceGroup": "observabilitytest",
        "resourceName": "telemetryasa",
        "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
    }
   ]
  },
  {
   "title": "ASA Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 9, "y": 49 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeserializationError",
      "metricNamespace": "microsoft.streamanalytics/streamingjobs",
      "region": "centralindia",
      "resources": [
       {
        "metricNamespace": "Microsoft.StreamAnalytics/streamingjobs",
        "region": "centralindia",
        "resourceGroup": "observabilitytest",
        "resourceName": "telemetryasa",
        "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ConversionErrors",
      "metricNamespace": "microsoft.streamanalytics/streamingjobs",
      "region": "centralindia",
      "resources": [
       {
        "metricNamespace": "Microsoft.StreamAnalytics/streamingjobs",
        "region": "centralindia",
        "resourceGroup": "observabilitytest",
        "resourceName": "telemetryasa",
        "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricNamespace": "microsoft.streamanalytics/streamingjobs",
      "region": "centralindia",
      "resources": [
       {
        "metricNamespace": "Microsoft.StreamAnalytics/streamingjobs",
        "region": "centralindia",
        "resourceGroup": "observabilitytest",
        "resourceName": "telemetryasa",
        "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "18eef2d8-17bc-45cf-b547-74e6ff722c5b"
    }
   ]
  }
 ]
}