FROM debian:bullseye-slim

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       curl ca-certificates apt-transport-https lsb-release gnupg make git bash \
       libicu67 \
    && rm -rf /var/lib/apt/lists/*

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install bicep
RUN az bicep install

WORKDIR /workspace
ENTRYPOINT ["/bin/bash"]